(()=>{'use strict';
if(typeof seedValue!=='undefined'&&seedValue)return;
const LIBRARY_KEY='reader-articles-private-library-v1',DRAFT_KEY='reader-articles-studio-v1';
document.querySelector('.toolbar').insertAdjacentHTML('afterbegin','<button id="articleLibraryBtn">Draft library <span id="articleLibraryCount">0</span></button>');
document.body.insertAdjacentHTML('afterbegin','<aside class="article-library" id="articleLibrary" aria-hidden="true"><header><div><strong>Private article library</strong><small>Browser-local drafts · separate from published articles</small></div><button id="closeArticleLibrary" aria-label="Close library">×</button></header><input id="articleLibrarySearch" type="search" placeholder="Search title, date, type, or byline"><div id="articleLibraryEntries"></div></aside>');
const byId=id=>document.getElementById(id),drawer=byId('articleLibrary'),entriesBox=byId('articleLibraryEntries'),search=byId('articleLibrarySearch');let library=readLibrary(),captureTimer;
function readLibrary(){try{const value=JSON.parse(localStorage.getItem(LIBRARY_KEY));if(value&&value.schema==='reader-article-library-v1'&&Array.isArray(value.entries))return value}catch{}return{schema:'reader-article-library-v1',activeId:null,entries:[]}}
function safe(value=''){const node=document.createElement('div');node.textContent=String(value);return node.innerHTML}function safeAttr(value=''){return safe(value).replaceAll('"','&quot;')}
function writeLibrary(){localStorage.setItem(LIBRARY_KEY,JSON.stringify(library));byId('articleLibraryCount').textContent=library.entries.length;render()}
function current(){const value=state();value.id=localStorage.getItem(DRAFT_KEY+'-id')||value.id;return value}
function put(value,makeActive=true){const index=library.entries.findIndex(item=>item.id===value.id);if(index<0)library.entries.push(value);else library.entries[index]=value;if(makeActive)library.activeId=value.id;writeLibrary()}
function capture(){const value=current();localStorage.setItem(DRAFT_KEY+'-id',value.id);localStorage.setItem(DRAFT_KEY,JSON.stringify(value));put(value)}
function scheduleCapture(){clearTimeout(captureTimer);captureTimer=setTimeout(capture,850)}
function openLibrary(){capture();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');render();search.focus()}
function closeLibrary(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true')}
function render(){const query=search.value.trim().toLowerCase(),items=[...library.entries].filter(item=>{const meta=item.metadata||{};return!query||[meta.title,meta.date,meta.type,meta.byline].join(' ').toLowerCase().includes(query)}).sort((a,b)=>((b.metadata||{}).date||'').localeCompare(((a.metadata||{}).date||''))||(b.savedAt||'').localeCompare(a.savedAt||''));entriesBox.innerHTML=items.length?items.map(item=>{const meta=item.metadata||{};return`<article class="article-library-entry${item.id===library.activeId?' active':''}" data-id="${safeAttr(item.id)}"><button class="article-library-open"><span>${safe(meta.type||'Article')} · ${safe(meta.date||'Undated')}</span><strong>${safe(meta.title||'Untitled article')}</strong><small>${safe(meta.byline||(item.id===library.activeId?'Currently open':'Open draft'))}</small></button><button class="article-library-delete" title="Delete from this browser">Delete</button></article>`}).join(''):'<p class="article-library-empty">No matching drafts.</p>'}
function openEntry(id){if(id===library.activeId){closeLibrary();return}capture();const value=library.entries.find(item=>item.id===id);if(!value)return;localStorage.setItem(DRAFT_KEY+'-id',value.id);localStorage.setItem(DRAFT_KEY,JSON.stringify(value));library.activeId=value.id;load(value);statusBox.textContent='Opened from private draft library';writeLibrary();closeLibrary()}
function blank(){return{schema:'reader-article-v1',id:crypto.randomUUID(),savedAt:new Date().toISOString(),metadata:{type:'Article',date:new Date().toISOString().slice(0,10),title:'',byline:''},bodyHTML:'<h2>Introduction</h2><p>Begin writing your article here.</p>',footnotes:[],notes:'',splitPercent:50}}
function newEntry(){capture();const value=blank();localStorage.setItem(DRAFT_KEY+'-id',value.id);localStorage.setItem(DRAFT_KEY,JSON.stringify(value));load(value);statusBox.textContent='New private article';put(value);closeLibrary()}
function importEntry(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const value=JSON.parse(reader.result);if(value.schema!=='reader-article-v1')throw new Error('Unsupported backup format');capture();value.id=value.id||crypto.randomUUID();value.savedAt=value.savedAt||new Date().toISOString();localStorage.setItem(DRAFT_KEY+'-id',value.id);localStorage.setItem(DRAFT_KEY,JSON.stringify(value));load(value);statusBox.textContent='Imported into private draft library';put(value);closeLibrary()}catch(error){alert(error.message)}};reader.readAsText(file)}
function deleteEntry(id){const item=library.entries.find(value=>value.id===id),title=item?.metadata?.title||'Untitled article';if(!item||!confirm(`Delete “${title}” from this browser? Export a backup first if needed.`))return;library.entries=library.entries.filter(value=>value.id!==id);if(library.activeId===id){const next=[...library.entries].sort((a,b)=>(b.savedAt||'').localeCompare(a.savedAt||''))[0]||blank();if(!library.entries.length)library.entries.push(next);localStorage.setItem(DRAFT_KEY+'-id',next.id);localStorage.setItem(DRAFT_KEY,JSON.stringify(next));library.activeId=next.id;load(next)}writeLibrary()}
const stored=localStorage.getItem(DRAFT_KEY);if(stored)try{const value=JSON.parse(stored);value.id=value.id||localStorage.getItem(DRAFT_KEY+'-id')||crypto.randomUUID();localStorage.setItem(DRAFT_KEY+'-id',value.id);put(value)}catch{}
byId('articleLibraryBtn').onclick=openLibrary;byId('closeArticleLibrary').onclick=closeLibrary;search.oninput=render;entriesBox.onclick=event=>{const entry=event.target.closest('.article-library-entry');if(!entry)return;if(event.target.closest('.article-library-delete'))deleteEntry(entry.dataset.id);else if(event.target.closest('.article-library-open'))openEntry(entry.dataset.id)};
const originalSave=byId('saveBtn').onclick;byId('saveBtn').onclick=()=>{originalSave();capture()};byId('newBtn').onclick=newEntry;byId('importInput').onchange=event=>{importEntry(event.target.files[0]);event.target.value=''};
document.addEventListener('input',event=>{if(event.target.closest('#workspace'))scheduleCapture()});document.addEventListener('change',event=>{if(event.target.closest('#workspace'))scheduleCapture()});window.addEventListener('beforeunload',capture);writeLibrary();
})();
