const KEY='reader-articles-studio-v1',editor=document.getElementById('editor'),preview=document.getElementById('previewBody'),footnoteBox=document.getElementById('previewFootnotes'),notes=document.getElementById('notes'),statusBox=document.getElementById('status'),articleType=document.getElementById('articleType'),articleDate=document.getElementById('articleDate'),articleTitle=document.getElementById('articleTitle'),articleByline=document.getElementById('articleByline'),previewTitle=document.getElementById('previewTitle'),previewType=document.getElementById('previewType'),previewMeta=document.getElementById('previewMeta'),previewNote=document.getElementById('previewNote'),imageInput=document.getElementById('imageInput'),importInput=document.getElementById('importInput'),splitter=document.getElementById('splitter'),workspace=document.getElementById('workspace');
let footnotes=[],saveTimer,savedRange=null;
const fields=['articleType','articleDate','articleTitle','articleByline'];
function metadata(){return{type:articleType.value,date:articleDate.value,title:articleTitle.value,byline:articleByline.value}}
function state(){return{schema:'reader-article-v1',id:localStorage.getItem(KEY+'-id')||crypto.randomUUID(),savedAt:new Date().toISOString(),metadata:metadata(),bodyHTML:editor.innerHTML,footnotes,notes:notes.value,splitPercent:parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--left'))||50}}
function escapeText(value){const node=document.createElement('div');node.textContent=value||'';return node.innerHTML}
function sync(){const meta=metadata();preview.innerHTML=editor.innerHTML;preview.querySelectorAll('[contenteditable]').forEach(node=>node.removeAttribute('contenteditable'));previewTitle.textContent=meta.title||'Untitled Article';previewType.textContent=meta.type||'Reader article';previewMeta.textContent=[meta.byline,meta.date].filter(Boolean).join(' · ')||'Draft';footnoteBox.innerHTML=footnotes.length?'<h2>Footnotes</h2>'+footnotes.map((note,index)=>`<p><sup>${index+1}</sup> ${escapeText(note)}</p>`).join(''):'';previewNote.textContent=notes.value;previewNote.hidden=!notes.value.trim()}
function save(auto=true){const value=state();localStorage.setItem(KEY,JSON.stringify(value));localStorage.setItem(KEY+'-id',value.id);statusBox.textContent=(auto?'Autosaved ':'Saved ')+new Date().toLocaleTimeString()}
function changed(){sync();statusBox.textContent='Unsaved changes';clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(true),600)}
function load(value){const meta=value.metadata||{};articleType.value=meta.type||'Article';articleDate.value=meta.date||new Date().toISOString().slice(0,10);articleTitle.value=meta.title||'';articleByline.value=meta.byline||'';editor.innerHTML=value.bodyHTML||'<h2>Introduction</h2><p>Begin writing your article here.</p>';footnotes=Array.isArray(value.footnotes)?value.footnotes:[];notes.value=value.notes||'';if(value.splitPercent)setSplit(value.splitPercent);sync()}
function download(name,type,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function slug(){return(articleTitle.value||'reader_article').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||'reader_article'}
function remember(){const selection=getSelection();if(selection?.rangeCount&&editor.contains(selection.anchorNode))savedRange=selection.getRangeAt(0).cloneRange()}
function restore(){if(!savedRange)return false;const selection=getSelection();selection.removeAllRanges();selection.addRange(savedRange);return true}
function command(name,value=null){restore();document.execCommand(name,false,value);savedRange=null;changed();editor.focus()}
function addFootnote(){if(!restore()){alert('Place the cursor in the article first.');return}const note=prompt('Footnote text:','');if(!note)return;footnotes.push(note);document.execCommand('insertHTML',false,`<sup data-reader-footnote="${footnotes.length}">${footnotes.length}</sup>`);savedRange=null;changed()}
async function insertImage(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{restore();document.execCommand('insertHTML',false,`<figure><img src="${reader.result}" alt=""><figcaption contenteditable="true">Image caption</figcaption></figure>`);savedRange=null;changed()};reader.readAsDataURL(file)}
function setSplit(percent){const value=Math.max(28,Math.min(72,Number(percent)||50));document.documentElement.style.setProperty('--left',value+'%')}
document.addEventListener('selectionchange',remember);editor.addEventListener('input',changed);notes.addEventListener('input',changed);fields.forEach(id=>document.getElementById(id).addEventListener('input',changed));
document.querySelectorAll('[data-command]').forEach(button=>button.onclick=()=>command(button.dataset.command,button.dataset.value||null));
document.getElementById('clearFormat').onclick=()=>command('removeFormat');document.getElementById('footnoteBtn').onclick=addFootnote;document.getElementById('imageBtn').onclick=()=>imageInput.click();imageInput.onchange=event=>{insertImage(event.target.files[0]);event.target.value=''};
document.getElementById('saveBtn').onclick=()=>save(false);document.getElementById('exportBtn').onclick=()=>download(slug()+'_backup.json','application/json',JSON.stringify(state(),null,2));document.getElementById('importInput').onchange=event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const value=JSON.parse(reader.result);if(value.schema!=='reader-article-v1')throw new Error('Unsupported backup format');load(value);save(false)}catch(error){alert(error.message)}};reader.readAsText(file)};
document.getElementById('pdfBtn').onclick=()=>{sync();document.title=(articleTitle.value||'Reader Article')+' · PDF';window.print()};document.getElementById('newBtn').onclick=()=>{if(!confirm('Start a new article? Export a backup first if you need the current draft.'))return;localStorage.removeItem(KEY);localStorage.removeItem(KEY+'-id');footnotes=[];load({metadata:{type:'Article',date:new Date().toISOString().slice(0,10)},bodyHTML:'<h2>Introduction</h2><p>Begin writing your article here.</p>'});changed()};
splitter.addEventListener('pointerdown',event=>{splitter.setPointerCapture(event.pointerId);const move=e=>{const rect=workspace.getBoundingClientRect();setSplit((e.clientX-rect.left)/rect.width*100);sync()};const stop=()=>{splitter.removeEventListener('pointermove',move);save(true)};splitter.addEventListener('pointermove',move);splitter.addEventListener('pointerup',stop,{once:true})});
const stored=localStorage.getItem(KEY),wantsNew=new URLSearchParams(location.search).get('new')==='1';if(wantsNew&&(!stored||confirm('Start a new article? The current browser draft will be replaced after the new article is autosaved.'))){load({metadata:{type:'Article',date:new Date().toISOString().slice(0,10)},bodyHTML:'<p><br></p>'});statusBox.textContent='New article'}else if(stored){try{load(JSON.parse(stored));statusBox.textContent='Restored browser draft'}catch{localStorage.removeItem(KEY);load({metadata:{type:'Article',date:new Date().toISOString().slice(0,10)},bodyHTML:'<p><br></p>'})}}else load({metadata:{type:'Article',date:new Date().toISOString().slice(0,10)},bodyHTML:'<p><br></p>'});
