(()=>{'use strict';
const config=window.OFFLINE_READER_CONFIG||{},BOOK=config.book||'engineering-cybernetics',BOOK_TITLE=config.title||'Engineering Cybernetics',NOTES_KEY=`offline-reader-${BOOK}-notes-v1`,OPTIONS_KEY=`offline-reader-${BOOK}-options-v1`,formats={english:config.englishFormat||'pdf',chinese:config.chineseFormat||'pdf'};
const chapters=config.chapters||[['Preface',19,12],['Introduction',25,18],['Chapter 1',30,23],['Chapter 2',52,45],['Chapter 3',71,60],['Chapter 4',88,71],['Chapter 5',101,81],['Chapter 6',112,95],['Chapter 7',129,102],['Chapter 8',154,122],['Chapter 9',178,145],['Chapter 10',186,152],['Chapter 11',196,162],['Chapter 12',216,178],['Chapter 13',232,191],['Chapter 14',249,204],['Chapter 15',271,223],['Appendices',286,231]];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let notes=read(NOTES_KEY,[]),options=read(OPTIONS_KEY,{layout:config.defaultLayout||'english-first',remember:true}),undoStack=[],redoStack=[],urls={},epubBook,epubRendition;
function fileFormat(file,fallback='pdf'){const name=(file?.name||'').toLowerCase();if(file?.type==='application/epub+zip'||name.endsWith('.epub'))return'epub';if(file?.type==='application/pdf'||name.endsWith('.pdf'))return'pdf';return fallback}
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function persist(){localStorage.setItem(NOTES_KEY,JSON.stringify(notes));$('#saveStatus').textContent='Notes saved on this device';renderNotes()}
function snapshot(){undoStack.push(JSON.stringify(notes));if(undoStack.length>30)undoStack.shift();redoStack=[];historyButtons()}function historyButtons(){$('#undo').disabled=!undoStack.length;$('#redo').disabled=!redoStack.length}
function restore(from,to){if(!from.length)return;to.push(JSON.stringify(notes));notes=JSON.parse(from.pop());persist();historyButtons()}
function escapeHTML(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openDrawer(form=false){$('#notesDrawer').classList.add('open');$('#notesDrawer').setAttribute('aria-hidden','false');$('#noteForm').hidden=!form;if(form)setTimeout(()=>$('#noteText').focus(),0)}function closeDrawer(){$('#notesDrawer').classList.remove('open');$('#notesDrawer').setAttribute('aria-hidden','true')}
function beginNote(){const edition=$('#workspace').dataset.layout==='chinese-only'?'chinese':'english';$('#editingId').value='';$('#noteEdition').value=edition;$('#notePage').value=$(`#${edition}Page`).value;$('#noteKind').value='Note';$('#noteQuote').value='';$('#noteText').value='';openDrawer(true)}
function renderNotes(){const q=$('#noteSearch').value.trim().toLowerCase();const visible=notes.filter(n=>!q||JSON.stringify(n).toLowerCase().includes(q)).sort((a,b)=>b.updated.localeCompare(a.updated));$('#noteCount').textContent=notes.length;$('#drawerSubtitle').textContent=q?`${visible.length} matching notes`:`${notes.length} saved notes`;$('#notesList').innerHTML=visible.length?visible.map(n=>`<article class="note-card" data-id="${n.id}"><header><strong>${escapeHTML(n.edition)} p. ${escapeHTML(n.page||'—')}</strong><span class="kind">${escapeHTML(n.kind)}</span><time>${new Date(n.updated).toLocaleDateString()}</time></header>${n.quote?`<blockquote>${escapeHTML(n.quote)}</blockquote>`:''}<p>${escapeHTML(n.text).replace(/\n/g,'<br>')}</p><footer><button data-edit>Edit</button><button data-delete>Delete</button></footer></article>`).join(''):'<div class="empty-notes">No notes yet. Attachments are optional—your notes remain available in this online workspace.</div>'}
function editNote(id){const n=notes.find(x=>x.id===id);if(!n)return;$('#editingId').value=n.id;$('#noteEdition').value=n.edition;$('#notePage').value=n.page;$('#noteKind').value=n.kind;$('#noteQuote').value=n.quote;$('#noteText').value=n.text;openDrawer(true)}
function saveOptions(){options.layout=$('#workspace').dataset.layout;options.remember=$('#rememberFiles').checked;localStorage.setItem(OPTIONS_KEY,JSON.stringify(options))}
function setLayout(v){$('#workspace').dataset.layout=v;saveOptions();$('#layoutMenu').hidden=true;requestAnimationFrame(()=>epubRendition?.resize())}
function go(edition){if(formats[edition]==='epub'){const target=chapters[$('#chapter').value]?.[1];if(epubRendition&&target)epubRendition.display(target);return}const page=Math.max(1,Number($(`#${edition}Page`).value)||1),viewer=$(`#${edition}Viewer`);viewer.dataset.page=page;if(urls[edition])viewer.src=`${urls[edition]}#page=${page}&view=FitH`}
function db(){return new Promise((resolve,reject)=>{const req=indexedDB.open('offline-reader-files',1);req.onupgradeneeded=()=>req.result.createObjectStore('pdfs');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function storeFile(edition,file){const d=await db();await new Promise((res,rej)=>{const tx=d.transaction('pdfs','readwrite');tx.objectStore('pdfs').put(file,`${BOOK}-${edition}`);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}
async function loadStored(edition){const d=await db(),value=await new Promise((res,rej)=>{const q=d.transaction('pdfs').objectStore('pdfs').get(`${BOOK}-${edition}`);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});d.close();if(value)showFile(edition,value)}
async function removeFile(edition){const d=await db();await new Promise((res,rej)=>{const tx=d.transaction('pdfs','readwrite');tx.objectStore('pdfs').delete(`${BOOK}-${edition}`);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close();if(urls[edition])URL.revokeObjectURL(urls[edition]);delete urls[edition];epubRendition?.destroy();epubBook?.destroy();epubRendition=epubBook=null;$('#englishEpubViewer')?.replaceChildren();$(`#${edition}Viewer`).removeAttribute('src');$(`.${edition}-pane`).classList.remove('loaded','format-epub','format-pdf');$(`#${edition}State`).textContent='No book file attached';$(`[data-remove=${edition}]`).hidden=true}
async function showEpub(file){if(typeof ePub!=='function')throw Error('EPUB reader is unavailable');epubRendition?.destroy();epubBook?.destroy();const data=await file.arrayBuffer();epubBook=ePub();await epubBook.open(data,'binary');epubRendition=epubBook.renderTo('englishEpubViewer',{width:'100%',height:'100%',flow:'paginated',spread:'none'});epubRendition.themes.default({'html, body':{'overflow':'hidden !important','max-width':'100% !important'},body:{margin:'0 auto !important',padding:'1.5rem 2rem !important','box-sizing':'border-box !important'},img:{'max-width':'100% !important',height:'auto !important'}});await epubRendition.display(chapters[$('#chapter').value]?.[1]);epubRendition.on('relocated',location=>{$('#englishPage').value=location.start.index+1;$(`#englishState`).textContent=`${file.name} · section ${location.start.index+1}`})}
async function showFile(edition,file){const format=fileFormat(file,formats[edition]);formats[edition]=format;if(format==='epub'&&$('#workspace').dataset.layout==='chinese-only')setLayout('balanced');const pane=$(`.${edition}-pane`);pane.classList.remove('format-epub','format-pdf');pane.classList.add('loaded',`format-${format}`);$(`#${edition}State`).textContent=file.name||`${format.toUpperCase()} stored on device`;$(`[data-remove=${edition}]`).hidden=false;if(format==='epub'){try{await showEpub(file)}catch(e){console.error(e);pane.classList.remove('loaded');alert('This EPUB could not be opened. You can attach the PDF edition instead.')}return}if(urls[edition])URL.revokeObjectURL(urls[edition]);urls[edition]=URL.createObjectURL(file);go(edition)}
async function attach(edition,file){if(!file)return;const format=fileFormat(file,'');if(!format||(edition==='chinese'&&format!=='pdf'))return alert(edition==='english'?'Please select an EPUB or PDF file.':'Please select a PDF file.');formats[edition]=format;if(format==='epub'&&$('#workspace').dataset.layout==='chinese-only')setLayout('balanced');await showFile(edition,file);if($('#rememberFiles').checked)try{await storeFile(edition,file)}catch(e){console.warn(e);alert(`The ${format.toUpperCase()} opened, but this browser could not store it permanently. Your notes will still be saved.`)}}
function exportBackup(){const blob=new Blob([JSON.stringify({format:'offline-reader-notes',version:1,book:BOOK,exported:new Date().toISOString(),notes,options},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${BOOK}-notes-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importBackup(file){if(!file)return;try{const data=JSON.parse(await file.text());if(data.book!==BOOK||!Array.isArray(data.notes))throw Error();snapshot();notes=data.notes;persist();openDrawer()}catch{alert(`This is not a valid ${BOOK_TITLE} notes backup.`)}}
chapters.forEach(([name,en,zh],i)=>$('#chapter').insertAdjacentHTML('beforeend',`<option value="${i}">${name}</option>`));if(chapters[0]){$('#englishPage').value=chapters[0][1]||1;$('#chinesePage').value=chapters[0][2]||1}$('#chapter').onchange=e=>{const c=chapters[e.target.value];$('#englishPage').value=c[1]||1;$('#chinesePage').value=c[2]||1;go('english');go('chinese')};
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-epub-nav]').forEach(b=>b.onclick=()=>epubRendition?.[b.dataset.epubNav]());$$('[data-layout]').forEach(b=>b.onclick=()=>setLayout(b.dataset.layout));$$('[data-remove]').forEach(b=>b.onclick=()=>confirm(`Remove the stored ${b.dataset.remove} ${formats[b.dataset.remove].toUpperCase()} from this browser? Your notes will remain.`)&&removeFile(b.dataset.remove));
$('#englishFile').onchange=e=>attach('english',e.target.files[0]);$('#chineseFile').onchange=e=>attach('chinese',e.target.files[0]);$('#addNote').onclick=beginNote;$('#showNotes').onclick=()=>openDrawer();$('#closeNotes').onclick=closeDrawer;$('#cancelNote').onclick=()=>{$('#noteForm').hidden=true};$('#noteSearch').oninput=()=>{renderNotes();openDrawer()};
$('#noteForm').onsubmit=e=>{e.preventDefault();snapshot();const id=$('#editingId').value,old=notes.find(n=>n.id===id),now=new Date().toISOString(),record={id:id||crypto.randomUUID(),edition:$('#noteEdition').value,page:Number($('#notePage').value)||'',kind:$('#noteKind').value,quote:$('#noteQuote').value.trim(),text:$('#noteText').value.trim(),created:old?.created||now,updated:now};notes=id?notes.map(n=>n.id===id?record:n):[...notes,record];persist();$('#noteForm').hidden=true};
$('#notesList').onclick=e=>{const card=e.target.closest('.note-card');if(!card)return;if(e.target.matches('[data-edit]'))editNote(card.dataset.id);if(e.target.matches('[data-delete]')&&confirm('Delete this note?')){snapshot();notes=notes.filter(n=>n.id!==card.dataset.id);persist()}};
$('#undo').onclick=()=>restore(undoStack,redoStack);$('#redo').onclick=()=>restore(redoStack,undoStack);$('#collapseToolbar').onclick=()=>{$('#toolbar').classList.toggle('compact');$('#collapseToolbar').textContent=$('#toolbar').classList.contains('compact')?'Expand toolbar':'Collapse toolbar'};
$('#layoutButton').onclick=()=>{$('#layoutMenu').hidden=!$('#layoutMenu').hidden;$('#settingsMenu').hidden=true};$('#settingsButton').onclick=()=>{$('#settingsMenu').hidden=!$('#settingsMenu').hidden;$('#layoutMenu').hidden=true};$('#exportBackup').onclick=exportBackup;$('#importBackup').onchange=e=>importBackup(e.target.files[0]);$('#rememberFiles').checked=options.remember!==false;
$('#clearNotes').onclick=()=>{if(notes.length&&confirm('Delete every note for this book on this browser? Export a backup first if needed.')){snapshot();notes=[];persist()}};
setLayout(options.layout||'english-first');renderNotes();historyButtons();if(options.remember!==false){loadStored('english').catch(console.warn);loadStored('chinese').catch(console.warn)}window.addEventListener('beforeunload',()=>Object.values(urls).forEach(URL.revokeObjectURL));
})();
