(()=>{'use strict';
const LIBRARY_KEY='personal-writings-library-v1',DRAFT_KEY='personal-writings-studio-v1';
document.querySelector('.toolbar').insertAdjacentHTML('afterbegin','<button id="libraryBtn">Library <span id="libraryCount">0</span></button>');
document.body.insertAdjacentHTML('afterbegin','<aside class="writing-library" id="writingLibrary" aria-hidden="true"><header><div><strong>Private writing library</strong><small>Stored only in this browser</small></div><button id="closeLibrary" aria-label="Close library">×</button></header><input id="librarySearch" type="search" placeholder="Search title, date, or writing type"><div id="libraryEntries"></div></aside>');
const byId=id=>document.getElementById(id),drawer=byId('writingLibrary'),entriesBox=byId('libraryEntries'),search=byId('librarySearch');let library=readLibrary(),captureTimer;
function readLibrary(){try{const value=JSON.parse(localStorage.getItem(LIBRARY_KEY));if(value&&value.schema==='personal-writing-library-v1'&&Array.isArray(value.entries))return value}catch{}return{schema:'personal-writing-library-v1',activeId:null,entries:[]}}
function writeLibrary(){localStorage.setItem(LIBRARY_KEY,JSON.stringify(library));byId('libraryCount').textContent=library.entries.length;render()}
function safe(value=''){const node=document.createElement('div');node.textContent=String(value);return node.innerHTML}function safeAttr(value=''){return safe(value).replaceAll('"','&quot;')}
function current(){const value=state();value.id=localStorage.getItem(DRAFT_KEY+'-id')||value.id;return value}
function put(value,makeActive=true){const index=library.entries.findIndex(item=>item.id===value.id);if(index<0)library.entries.push(value);else library.entries[index]=value;if(makeActive)library.activeId=value.id;writeLibrary()}
function capture(){const value=current();localStorage.setItem(DRAFT_KEY+'-id',value.id);localStorage.setItem(DRAFT_KEY,JSON.stringify(value));put(value)}
function scheduleCapture(){clearTimeout(captureTimer);captureTimer=setTimeout(capture,850)}
function openLibrary(){capture();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');render();search.focus()}
function closeLibrary(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true')}
function render(){const query=search.value.trim().toLowerCase(),items=[...library.entries].filter(item=>!query||[item.title,item.date,item.type].join(' ').toLowerCase().includes(query)).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.savedAt||'').localeCompare(a.savedAt||''));entriesBox.innerHTML=items.length?items.map(item=>`<article class="library-entry${item.id===library.activeId?' active':''}" data-id="${safeAttr(item.id)}"><button class="library-open"><span>${safe(item.type||'Writing')} · ${safe(item.date||'Undated')}</span><strong>${safe(item.title||item.type||'Untitled writing')}</strong><small>${item.id===library.activeId?'Currently open':'Open entry'}</small></button><button class="library-delete" title="Delete from this browser">Delete</button></article>`).join(''):'<p class="library-empty">No matching entries.</p>'}
function openEntry(id){if(id===library.activeId){closeLibrary();return}capture();const value=library.entries.find(item=>item.id===id);if(!value)return;localStorage.setItem(DRAFT_KEY+'-id',value.id);localStorage.setItem(DRAFT_KEY,JSON.stringify(value));library.activeId=value.id;load(value);statusBox.textContent='Opened from private library';writeLibrary();closeLibrary()}
function newEntry(){capture();const id=crypto.randomUUID(),value={schema:'personal-writing-v1',id,type:'Diary',date:new Date().toISOString().slice(0,10),title:'',details:{},bodyHTML:'<p><br></p>',schedule:[],footnotes:[],notes:'',splitPercent:50,savedAt:new Date().toISOString()};localStorage.setItem(DRAFT_KEY+'-id',id);localStorage.setItem(DRAFT_KEY,JSON.stringify(value));load(value);statusBox.textContent='New private writing';put(value);closeLibrary()}
function importEntry(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const value=JSON.parse(reader.result);if(value.schema!=='personal-writing-v1')throw new Error('Unsupported backup format');capture();value.id=value.id||crypto.randomUUID();value.savedAt=value.savedAt||new Date().toISOString();localStorage.setItem(DRAFT_KEY+'-id',value.id);localStorage.setItem(DRAFT_KEY,JSON.stringify(value));load(value);statusBox.textContent='Imported into private library';put(value);closeLibrary()}catch(error){alert(error.message)}};reader.readAsText(file)}
function deleteEntry(id){const item=library.entries.find(value=>value.id===id);if(!item||!confirm(`Delete “${item.title||item.type||'Untitled writing'}” from this browser? Export a backup first if needed.`))return;library.entries=library.entries.filter(value=>value.id!==id);if(library.activeId===id){library.activeId=null;if(library.entries.length){const next=[...library.entries].sort((a,b)=>(b.savedAt||'').localeCompare(a.savedAt||''))[0];localStorage.setItem(DRAFT_KEY+'-id',next.id);localStorage.setItem(DRAFT_KEY,JSON.stringify(next));library.activeId=next.id;load(next)}else{const value={schema:'personal-writing-v1',id:crypto.randomUUID(),type:'Diary',date:new Date().toISOString().slice(0,10),bodyHTML:'<p><br></p>'};localStorage.setItem(DRAFT_KEY+'-id',value.id);load(value);put(current())}}writeLibrary()}
const stored=localStorage.getItem(DRAFT_KEY);if(stored)try{const value=JSON.parse(stored);value.id=value.id||localStorage.getItem(DRAFT_KEY+'-id')||crypto.randomUUID();localStorage.setItem(DRAFT_KEY+'-id',value.id);put(value)}catch{}
byId('libraryBtn').onclick=openLibrary;byId('closeLibrary').onclick=closeLibrary;search.oninput=render;entriesBox.onclick=event=>{const entry=event.target.closest('.library-entry');if(!entry)return;if(event.target.closest('.library-delete'))deleteEntry(entry.dataset.id);else if(event.target.closest('.library-open'))openEntry(entry.dataset.id)};
const originalSave=byId('saveBtn').onclick;byId('saveBtn').onclick=()=>{originalSave();capture()};byId('newBtn').onclick=newEntry;byId('importInput').onchange=event=>{importEntry(event.target.files[0]);event.target.value=''};
document.addEventListener('input',event=>{if(event.target.closest('#workspace'))scheduleCapture()});document.addEventListener('change',event=>{if(event.target.closest('#workspace'))scheduleCapture()});window.addEventListener('beforeunload',capture);writeLibrary();
})();
