const KEY='personal-writings-studio-v1';
const $=id=>document.getElementById(id),editor=$('editor'),notes=$('notes'),writingType=$('writingType'),writingDate=$('writingDate'),writingTitle=$('writingTitle'),detailFields=$('detailFields'),scheduleEditor=$('scheduleEditor'),scheduleRows=$('scheduleRows'),previewSchedule=$('previewSchedule'),statusBox=$('status'),splitter=$('splitter'),workspace=$('workspace'),importInput=$('importInput');
let saveTimer,savedRange=null,schedule=[];
const templates={
  'Diary':{details:[['Location','location'],['Mood or theme','mood']],label:'Diary entry',body:'<p>What happened today?</p><p>What did I notice or feel?</p>'},
  'Schedule':{details:[['Main goal','goal'],['Date range','range']],label:'Schedule overview',body:'<p>Describe the purpose of this schedule and any important constraints.</p>'},
  'Journal':{details:[['Topic','topic'],['Entry number','number']],label:'Journal entry',body:'<p>Record observations, questions, and developing ideas.</p>'},
  'Reflection':{details:[['Experience','experience'],['Focus','focus']],label:'Reflection',body:'<h2>What happened?</h2><p></p><h2>What did I learn?</h2><p></p><h2>What will I do next?</h2><p></p>'},
  'Reading Notes':{details:[['Book or source','source'],['Pages or section','pages']],label:'Reading notes',body:'<h2>Summary</h2><p></p><h2>Important passages</h2><p></p><h2>Questions</h2><p></p>'},
  'Meeting Notes':{details:[['Participants','participants'],['Location or link','location']],label:'Meeting notes',body:'<h2>Agenda</h2><p></p><h2>Decisions</h2><p></p><h2>Action items</h2><p></p>'}
};
function escapeText(value){const node=document.createElement('div');node.textContent=value||'';return node.innerHTML}
function escapeAttr(value){return escapeText(value).replaceAll('"','&quot;')}
function details(){return Object.fromEntries([...detailFields.querySelectorAll('input')].map(input=>[input.name,input.value]))}
function renderDetails(values={}){const item=templates[writingType.value];detailFields.innerHTML=item.details.map(([label,name])=>`<label>${label}<input name="${name}" value="${escapeAttr(values[name]||'')}"></label>`).join('');detailFields.querySelectorAll('input').forEach(input=>input.addEventListener('input',changed));$('editorLabel').textContent=item.label;scheduleEditor.classList.toggle('hidden',writingType.value!=='Schedule')}
function renderSchedule(){scheduleRows.innerHTML=schedule.map((row,index)=>`<div class="schedule-row" data-index="${index}"><input type="time" data-field="time" value="${escapeAttr(row.time)}"><input data-field="item" value="${escapeAttr(row.item)}" placeholder="Task or appointment"><select data-field="priority"><option${row.priority==='Normal'?' selected':''}>Normal</option><option${row.priority==='High'?' selected':''}>High</option><option${row.priority==='Low'?' selected':''}>Low</option></select><span><select data-field="status"><option${row.status==='Planned'?' selected':''}>Planned</option><option${row.status==='Done'?' selected':''}>Done</option><option${row.status==='Deferred'?' selected':''}>Deferred</option></select> <button class="schedule-remove" data-remove="${index}">×</button></span></div>`).join('');scheduleRows.querySelectorAll('[data-field]').forEach(input=>input.addEventListener('input',event=>{schedule[Number(event.target.closest('.schedule-row').dataset.index)][event.target.dataset.field]=event.target.value;changed()}));scheduleRows.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{schedule.splice(Number(button.dataset.remove),1);renderSchedule();changed()})}
function state(){return{schema:'personal-writing-v1',id:localStorage.getItem(KEY+'-id')||crypto.randomUUID(),savedAt:new Date().toISOString(),type:writingType.value,date:writingDate.value,title:writingTitle.value,details:details(),bodyHTML:editor.innerHTML,schedule,notes:notes.value,splitPercent:parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--left'))||50}}
function sync(){const info=details();$('previewType').textContent=writingType.value;$('previewTitle').textContent=writingTitle.value||writingType.value;$('previewMeta').textContent=writingDate.value||'Undated';$('previewDetails').innerHTML=Object.entries(info).filter(([,value])=>value.trim()).map(([key,value])=>`<span>${escapeText(key)}: ${escapeText(value)}</span>`).join('');$('previewBody').innerHTML=editor.innerHTML;const isSchedule=writingType.value==='Schedule';previewSchedule.classList.toggle('hidden',!isSchedule);previewSchedule.querySelector('tbody').innerHTML=schedule.map(row=>`<tr><td>${escapeText(row.time)}</td><td>${escapeText(row.item)}</td><td>${escapeText(row.priority)}</td><td>${escapeText(row.status)}</td></tr>`).join('');$('previewNote').textContent=notes.value;$('previewNote').hidden=!notes.value.trim()}
function save(auto=true){const value=state();localStorage.setItem(KEY,JSON.stringify(value));localStorage.setItem(KEY+'-id',value.id);statusBox.textContent=(auto?'Autosaved ':'Saved ')+new Date().toLocaleTimeString()}
function changed(){sync();statusBox.textContent='Unsaved changes';clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(true),600)}
function load(value){writingType.value=value.type||'Diary';writingDate.value=value.date||new Date().toISOString().slice(0,10);writingTitle.value=value.title||'';renderDetails(value.details||{});editor.innerHTML=value.bodyHTML||templates[writingType.value].body;schedule=Array.isArray(value.schedule)?value.schedule:[];notes.value=value.notes||'';if(value.splitPercent)setSplit(value.splitPercent);renderSchedule();sync()}
function setSplit(value){document.documentElement.style.setProperty('--left',Math.max(28,Math.min(72,Number(value)||50))+'%')}
function download(name,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function remember(){const selection=getSelection();if(selection?.rangeCount&&editor.contains(selection.anchorNode))savedRange=selection.getRangeAt(0).cloneRange()}
function command(name,value=null){if(savedRange){const selection=getSelection();selection.removeAllRanges();selection.addRange(savedRange)}document.execCommand(name,false,value);savedRange=null;changed()}
document.addEventListener('selectionchange',remember);editor.addEventListener('input',changed);notes.addEventListener('input',changed);writingDate.addEventListener('input',changed);writingTitle.addEventListener('input',changed);writingType.addEventListener('change',()=>{const current=templates[writingType.value];renderDetails();editor.innerHTML=current.body;if(writingType.value==='Schedule'&&!schedule.length)schedule=[{time:'09:00',item:'',priority:'Normal',status:'Planned'}];renderSchedule();changed()});document.querySelectorAll('[data-command]').forEach(button=>button.onclick=()=>command(button.dataset.command,button.dataset.value||null));$('clearFormat').onclick=()=>command('removeFormat');$('addSchedule').onclick=()=>{schedule.push({time:'09:00',item:'',priority:'Normal',status:'Planned'});renderSchedule();changed()};$('saveBtn').onclick=()=>save(false);$('exportBtn').onclick=()=>download((writingType.value.toLowerCase().replace(/\s+/g,'_'))+'_backup.json',JSON.stringify(state(),null,2));importInput.onchange=event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const value=JSON.parse(reader.result);if(value.schema!=='personal-writing-v1')throw new Error('Unsupported backup format');load(value);save(false)}catch(error){alert(error.message)}};reader.readAsText(file)};$('pdfBtn').onclick=()=>{sync();document.title=(writingTitle.value||writingType.value)+' · PDF';window.print()};$('newBtn').onclick=()=>{if(!confirm('Start a new private writing? Export a backup first if needed.'))return;localStorage.removeItem(KEY);localStorage.removeItem(KEY+'-id');schedule=[];load({type:'Diary',date:new Date().toISOString().slice(0,10)});changed()};splitter.addEventListener('pointerdown',event=>{splitter.setPointerCapture(event.pointerId);const move=e=>{const rect=workspace.getBoundingClientRect();setSplit((e.clientX-rect.left)/rect.width*100)};splitter.addEventListener('pointermove',move);splitter.addEventListener('pointerup',()=>{splitter.removeEventListener('pointermove',move);save(true)},{once:true})});
const stored=localStorage.getItem(KEY),wantsNew=new URLSearchParams(location.search).get('new')==='1';if(wantsNew&&(!stored||confirm('Start a new writing? The current browser draft will be replaced after the new writing is autosaved.'))){load({type:'Diary',date:new Date().toISOString().slice(0,10),bodyHTML:'<p><br></p>'});statusBox.textContent='New private writing'}else if(stored){try{load(JSON.parse(stored));statusBox.textContent='Restored private browser draft'}catch{localStorage.removeItem(KEY);load({type:'Diary',date:new Date().toISOString().slice(0,10),bodyHTML:'<p><br></p>'})}}else load({type:'Diary',date:new Date().toISOString().slice(0,10),bodyHTML:'<p><br></p>'});
